feat: remove errors from infallible sdk functions
filecoin-project/ref-fvm pull request #274
Opened 2022-01-18 21:04 UTC by Stebalien

Either:

1. These functions statically cannot fail (https://github.com/filecoin-project/fvm-specs/issues/580 to follow up on this).
2. These functions can only fail when passed invalid data that we've ensured is statically impossible with the type system.

fixes #190

2022-01-18 21:04 UTC, Stebalien commented
I'm fixing this _now_ as part of my effort to remove fatal errors from the actors.

2022-01-18 21:38 UTC, Stebalien commented
> I'm fixing this now as part of my effort to remove fatal errors from the actors.

Eh, that commit is small enough that I've just tacked it onto this PR.

2022-01-19 17:23 UTC, laudiacay commented on actors/runtime/src/test_utils.rs
> +        ()
clippy is complaining about this

2022-01-19 17:24 UTC, laudiacay requested changes
nice, cleans things up a lot :D have a few nits and they're all clippy warnings but i think this is ready to merge otherwise

2022-01-19 18:11 UTC, laudiacay approved these changes

2022-01-19 18:11 UTC, merged