Tweak self-transfer behaviour to match v15
filecoin-project/ref-fvm pull request #364
Opened 2022-03-07 16:52 UTC by arajasek

Closes #143

Matches behaviour in https://github.com/filecoin-project/lotus/pull/7637.

The motivation for this change is mostly around UX -- it appears weird when people successfully send themselves 2B Filecoin, even though no actual transfer occurs. This change is slightly less efficient than exiting early on self-transfers, but that's not really a case we're looking to optimize.

2022-03-08 00:33 UTC, Stebalien approved these changes
LGTM. Do we know of any such messages on-chain? I.e., should this be behind a version guard?

NOTE: we can always remove such version guards later, but it's still useful to be able to sync/debug against chain history for now.

2022-03-08 00:33 UTC, Stebalien commented on fvm/src/machine/default.rs
> +        if from_actor.balance.lt(value) {
Can we not just use `from_actor.balance < value`?

2022-03-08 02:24 UTC, jennijuju commented
> LGTM. Do we know of any such messages on-chain? I.e., should this be behind a version guard?
> 
> NOTE: we can always remove such version guards later, but it's still useful to be able to sync/debug against chain history for now.

I.e https://m.filscout.com/zh/message/bafy2bzacebr2quxfina5pcy3uudh5lhrbapmbdaxd3l5qfkfhaun6yq44qxmu

2022-03-09 13:12 UTC, raulk requested changes
Let's add a version guard. ref-fvm officially supports nv14 and above, and this would break support for nv14. (And we should extract a test vector from that message.)

2022-03-09 16:12 UTC, arajasek commented
Yeah, opened this before the discussion that resulted in https://github.com/filecoin-project/ref-fvm/pull/360#discussion_r821077448

2022-03-09 16:24 UTC, arajasek commented
Pulling into #360

2022-03-09 16:24 UTC, closed without merging